apiVersion: v1
kind: Service
metadata:
  name: mlb-mcp-server
  labels:
    app.kubernetes.io/name: mlb-mcp-server
spec:
  selector:
    app.kubernetes.io/name: mlb-mcp-server
  ports:
    - port: 9090
      name: http
      targetPort: 9090
  type: ClusterIP
