apiVersion: v1
kind: Secret
metadata:
  name: pipeline-s3-credentials
  labels:
    app.kubernetes.io/name: mlb-eval-pipeline
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio1234
